"""Created by Vishal Dogra on 30-06-2020"""

USER_AGENT_CLIENT = "Mozilla"
USER_AGENT_CLIENT_VERSION = "5.0"
SYSTEM_INFORMATION = "Windows NT 10.0; Win64; x64"
BASE_URL = "https://www.myntra.com"
HEADPHONES = "headphones"
HOME_DECOR = "home-decor"
BOYS_T_SHIRT = "boys-tshirts"
DELIMITER = "/"
